### ISSUE TITLE
Error at running

### ISSUE THREAD

**Issue by azayed** [amorican/titanium-mapbox-android#2]
Hello, 

we have built your module and it seemed that everything built ok. We include the built module in the app, but when we try to run it it gives an error. Could you please share the module built  so we can included it directly into the app?

Here is the error at run time

[ERROR] :  TiApplication: (main) [42,388] Sending event: exception on thread: main msg:java.lang.NoClassDefFoundError: com.mapbox.mapboxsdk.R$drawable; Titanium 3.2.3,2014/04/22 10:17,b958a70
[ERROR] :  TiApplication: java.lang.NoClassDefFoundError: com.mapbox.mapboxsdk.R$drawable
[ERROR] :  TiApplication: at com.mapbox.mapboxsdk.views.MapView.<init>(MapView.java:166)
[ERROR] :  TiApplication: at com.mapbox.mapboxsdk.views.MapView.<init>(MapView.java:242)
[ERROR] :  TiApplication: at flg.mapbox.MapView.<init>(MapView.java:70)
[ERROR] :  TiApplication: at flg.mapbox.MapViewProxy.createView(MapViewProxy.java:43)
[ERROR] :  TiApplication: at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:463)
[ERROR] :  TiApplication: at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:449)
[ERROR] :  TiApplication: at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:487)
[ERROR] :  TiApplication: at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:471)
[ERROR] :  TiApplication: at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:449)
[ERROR] :  TiApplication: at org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:487)
[ERROR] :  TiApplication: at org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:471)
[ERROR] :  TiApplication: at org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:449)
[ERROR] :  TiApplication: at org.appcelerator.titanium.proxy.TiViewProxy.handleAdd(TiViewProxy.java:566)
[ERROR] :  TiApplication: at org.appcelerator.titanium.proxy.TiViewProxy.add(TiViewProxy.java:544)
[ERROR] :  TiApplication: at ti.modules.titanium.ui.WindowProxy.windowCreated(WindowProxy.java:303)
[ERROR] :  TiApplication: at org.appcelerator.titanium.TiActivityWindows.windowCreated(TiActivityWindows.java:32)
[ERROR] :  TiApplication: at org.appcelerator.titanium.TiBaseActivity.windowCreated(TiBaseActivity.java:452)
[ERROR] :  TiApplication: at org.appcelerator.titanium.TiBaseActivity.onCreate(TiBaseActivity.java:528)
[ERROR] :  TiApplication: at org.appcelerator.titanium.TiActivity.onCreate(TiActivity.java:18)
[ERROR] :  TiApplication: at android.app.Activity.performCreate(Activity.java:5203)
[ERROR] :  TiApplication: at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
[ERROR] :  TiApplication: at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2078)
[ERROR] :  TiApplication: at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2139)
[ERROR] :  TiApplication: at android.app.ActivityThread.access$700(ActivityThread.java:143)
[ERROR] :  TiApplication: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1241)
[ERROR] :  TiApplication: at android.os.Handler.dispatchMessage(Handler.java:99)
[ERROR] :  TiApplication: at android.os.Looper.loop(Looper.java:137)
[ERROR] :  TiApplication: at android.app.ActivityThread.main(ActivityThread.java:4960)
[ERROR] :  TiApplication: at java.lang.reflect.Method.invokeNative(Native Method)
[ERROR] :  TiApplication: at java.lang.reflect.Method.invoke(Method.java:511)
[ERROR] :  TiApplication: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
[ERROR] :  TiApplication: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
[ERROR] :  TiApplication: at dalvik.system.NativeStart.main(Native Method)

Thanks a lot!

**Comment by squirej** [comment]
Could you please share a compiled module to test with?

**Comment by reactnative103** [comment]
Hello Suirej,
Please check the same issue with my complied module.
[flg.mapbox.zip](https://github.com/amorican/titanium-mapbox-android/files/492455/flg.mapbox.zip)
